language: java
cache:
  timeout: 1000
  directories:
  - $HOME/.m2
dist: trusty
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - python3

install: ./cd/install.sh
script: ./cd/verify.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _book
  on:
    branch: master
