language: java
cache:
  timeout: 1000
  directories:
  - $HOME/.m2
dist: trusty
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - python3

install: ./cd/install.sh
script: ./cd/verify.sh
after_success: ./cd/deploy.sh