site_name: Gaffer Docs
repo_url: https://github.com/gchq/gaffer-doc
repo_name: gchq/gaffer-doc
edit_uri: edit/v2docs/docs/
copyright: Copyright &copy; 2016-2023 Crown Copyright
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gchq/gaffer
      name: Gaffer on GitHub
  version:
    provider: mike
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Europe/London
      strict: true
      exclude:
        - index.md

nav:
  - Home: "index.md"
  - "Gaffer 2.0":
      - Changelist: "gaffer2.0/changelist.md"
      - Deprecations: "gaffer2.0/deprecations.md"
      - Dependencies: "gaffer2.0/dependencies.md"
      - "Accumulo Migration": "gaffer2.0/accumulo-migration.md"
      - "Federation Changes": "gaffer2.0/federation-changes.md"
      - "Accumulo Kerberos": "gaffer2.0/accumulo-kerberos.md"
      - "Log4j in Gaffer": "gaffer2.0/log4j.md"
  - "Getting Started":
      - "Quickstart": "getting-started/quickstart.md"
      - "Gaffer Basics": "getting-started/basics.md"
      - "Gaffer Guide":
          - "Gaffer Guide": "getting-started/guide/guide.md"
          - "CSV Import and Export": "getting-started/guide/csv.md"
          - "Cardinality": "getting-started/guide/cardinality.md"
      - "Deploying Gaffer": "getting-started/deploying.md"
  - "Dev Info":
      - "Development": "dev/development.md"
      - "Managing Dependencies": "dev/managing-dependencies/managing-dependencies.md"
      - "Ways of Working": "dev/ways-of-working.md"
      - "Sketches custom deserialisation": "dev/rest-api-sketches.md"
      - "Docker": "dev/docker.md"
      - Components:
          - "Cache": "dev/components/cache.md"
          - "Data": "dev/components/data.md"
          - "Graph": "dev/components/graph.md"
          - "Store": "dev/components/store.md"
          - "Operation": "dev/components/operation.md"
          - "Serialisation": "dev/components/serialisation.md"
          - "Integration Tests": "dev/components/integration-test.md"
          - "Core REST": "dev/components/core-rest.md"
          - "Spring REST": "dev/components/spring-rest.md"
          - "Accumulo Store": "dev/components/accumulo-store.md"
          - Libraries:
              - dev/components/libraries/bitmap.md
              - dev/components/libraries/flink.md
              - dev/components/libraries/sketches.md
              - dev/components/libraries/spark.md
              - dev/components/libraries/time.md
      - Kubernetes:
          - "Kubernetes Guide": "dev/kubernetes-guide/kubernetes.md"
          - "Kind Deployment": "dev/kubernetes-guide/kind-deployment.md"
          - "AWS EKS Deployment": "dev/kubernetes-guide/aws-eks-deployment.md"
          - "Deploy an Empty Graph": "dev/kubernetes-guide/deploy-empty-graph.md"
          - "Add your schema": "dev/kubernetes-guide/deploy-schema.md"
          - "Change the Graph Id and Description": "dev/kubernetes-guide/change-graph-metadata.md"
          - "Adding your own libraries and functions": "dev/kubernetes-guide/add-libraries.md"
          - "Changing Accumulo Passwords": "dev/kubernetes-guide/change-accumulo-passwords.md"
  - "Reference":
      - "Reference Guide": "reference/intro.md"
      - Stores:
          - "Store Guide": "reference/stores-guide/stores.md"
          - "Map Store": "reference/stores-guide/map.md"
          - "Accumulo Store": "reference/stores-guide/accumulo.md"
          - "Proxy Store": "reference/stores-guide/proxy.md"
          - "Federated Store": "reference/stores-guide/federated.md"
      - Properties:
          - "Properties Guide": "reference/properties-guide/properties.md"
          - "Basic Properties": "reference/properties-guide/basic.md"
          - "Advanced Properties": "reference/properties-guide/advanced.md"
          - "Type Properties": "reference/properties-guide/type.md"
          - "Map & Set Properties": "reference/properties-guide/map-set.md"
      - Predicates:
          - "Predicates Guide": "reference/predicates-guide/predicates.md"
          - "Gaffer Predicates": "reference/predicates-guide/gaffer-predicates.md"
          - "Koryphe Predicates": "reference/predicates-guide/koryphe-predicates.md"
      - "Binary Operators":
          - "Binary Operators Guide": "reference/binary-operators-guide/binary-operators.md"
          - "Koryphe Operators Guide": "reference/binary-operators-guide/koryphe-operators.md"
      - Functions:
          - "Functions Guide": "reference/functions-guide/functions.md"
          - "Gaffer Functions": "reference/functions-guide/gaffer-functions.md"
          - "Koryphe Functions": "reference/functions-guide/koryphe-functions.md"
      - Operations:
          - "Operations Guide": "reference/operations-guide/operations.md"
          - "Core Operations": "reference/operations-guide/core.md"
          - "Join Operation": "reference/operations-guide/join.md"
          - "Get Operations": "reference/operations-guide/get.md"
          - "Control Flow Operations": "reference/operations-guide/flow.md"
          - "Job Operations": "reference/operations-guide/job.md"
          - "Named Operations": "reference/operations-guide/named.md"
          - "Export Operations": "reference/operations-guide/export.md"
          - "Generate Operations": "reference/operations-guide/generate.md"
          - "Flink Operations": "reference/operations-guide/flink.md"
          - "HDFS Operations": "reference/operations-guide/hdfs.md"
          - "Accumulo Operations": "reference/operations-guide/accumulo.md"
          - "Spark Operations": "reference/operations-guide/spark.md"
          - "Misc Operations": "reference/operations-guide/misc.md"

theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - content.action.edit
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle: &todark
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle: &tolight
        icon: material/weather-sunny
        name: Switch to light mode
