site_name: Gaffer Docs
repo_url: https://github.com/gchq/gaffer-doc
repo_name: gchq/gaffer-doc
edit_uri: edit/v2docs/docs/
copyright: Copyright &copy; 2016-2022 Crown Copyright
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gchq/gaffer
      name: Gaffer on GitHub
  version:
    provider: mike

nav:
    - Home: 'index.md'
    - Changelist: 'changelist.md'
    - Deprecations: 'deprecations.md'
    - Dependencies: 'dependencies.md'
    - 'Accumulo Migration': 'accumulo-migration.md'
    - Ways of Working: 'ways-of-working.md'

theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle: &todark
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle: &tolight
        icon: material/weather-sunny
        name: Switch to light mode
