site_name: Gaffer Docs
repo_url: https://github.com/gchq/gaffer-doc
repo_name: gchq/gaffer-doc
edit_uri: edit/v2docs/docs/
copyright: Copyright &copy; 2016-2023 Crown Copyright
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gchq/gaffer
      name: Gaffer on GitHub
  version:
    provider: mike
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Europe/London
      strict: true
      exclude:
        - index.md
  - redirects:
      redirect_maps:
        'dev/docker.md': 'administration-guide/where-to-run-gaffer/gaffer-docker.md'
        'dev/kubernetes-guide/kubernetes.md': 'administration-guide/where-to-run-gaffer/kubernetes-guide/kubernetes-guide.md'
        'dev/ways-of-working.md': 'development-guide/ways-of-working.md'
        'dev/components/operation.md': 'development-guide/project-structure/components/operation.md'
        'dev/components/cache.md': 'development-guide/project-structure/components/cache.md'
        'dev/components/graph.md': 'development-guide/project-structure/components/graph.md'
        'dev/components/data.md': 'development-guide/project-structure/components/data.md'
        'dev/components/store.md': 'development-guide/project-structure/components/store.md'
        'dev/components/serialisation.md': 'development-guide/project-structure/components/serialisation.md'
        'dev/components/libraries/sketches.md': 'development-guide/project-structure/components/libraries/sketches.md'
        'dev/components/libraries/bitmap.md': 'development-guide/project-structure/components/libraries/bitmap.md'
        'dev/components/libraries/time.md': 'development-guide/project-structure/components/libraries/time.md'
        'dev/components/libraries/flink.md': 'development-guide/project-structure/components/libraries/flink.md'
        'dev/components/libraries/spark.md': 'development-guide/project-structure/components/libraries/spark.md'
        'dev/components/integration-test.md': 'development-guide/project-structure/components/integration-test.md'
        'dev/components/spring-rest.md': 'development-guide/project-structure/components/spring-rest.md'
        'dev/components/core-rest.md': 'development-guide/project-structure/components/core-rest.md'
        'dev/components/accumulo-store.md': 'development-guide/project-structure/components/accumulo-store.md'
        'reference/stores-guide/stores.md': 'administration-guide/gaffer-stores/store-guide.md'
        'reference/stores-guide/map.md': 'administration-guide/gaffer-stores/map-store.md'
        'reference/stores-guide/proxy.md': 'administration-guide/gaffer-stores/proxy-store.md'
        'reference/stores-guide/federated.md': 'administration-guide/gaffer-stores/federated-store.md'
        'reference/stores-guide/accumulo.md': 'administration-guide/gaffer-stores/accumulo-store.md'
        'getting-started/basics.md': 'user-guide/introduction.md'
        'getting-started/guide/cardinality.md': 'user-guide/gaffer-basics/what-is-cardinality.md'
        'getting-started/quickstart.md': 'user-guide/introduction.md'
        'getting-started/guide/guide.md': 'user-guide/introduction.md'

nav:
    - Home: 'index.md'
    - User Guide:
      - 'Introduction': 'user-guide/introduction.md'
      - Gaffer Basics:
        - 'What is Gaffer?': 'user-guide/gaffer-basics/what-is-gaffer.md'
        - 'What is a Graph?': 'user-guide/gaffer-basics/what-is-a-graph.md'
        - 'What is JSON?': 'user-guide/gaffer-basics/what-is-json.md'
        - 'What is Python?': 'user-guide/gaffer-basics/what-is-python.md'
        - 'What is Cardinality?': 'user-guide/gaffer-basics/what-is-cardinality.md'
        - 'What is Aggregation?': 'user-guide/gaffer-basics/what-is-aggregation.md'
      - Available APIs:
        - 'Spring REST': 'user-guide/apis/rest-api.md'
        - 'Python (gafferpy)': 'user-guide/apis/python-api.md'
        - 'Java': 'user-guide/apis/java-api.md'
      - Querying:
        - Gaffer Query Syntax:
          - 'Operations': 'user-guide/query/gaffer-syntax/operations.md'
          - 'Filtering Data': 'user-guide/query/gaffer-syntax/filtering.md'
          - Import/Export:
            - 'Using CSV Data': 'user-guide/query/gaffer-syntax/import-export/csv.md'
        - Apache Gremlin:
          - 'Gremlin Support in Gaffer': 'user-guide/query/gremlin/gremlin.md'
      - 'Graph Schemas': 'user-guide/schema.md'
    - Developers Guide:
      - 'Introduction': 'development-guide/introduction.md'
      - 'Example Deployment':
        - 'Project Setup': 'getting-started/example-deployment/project-setup.md'
        - 'Writing the Schema': 'getting-started/example-deployment/writing-the-schema.md'
        - 'Running the Deployment': 'getting-started/example-deployment/running-the-deployment.md'
        - 'Using the API': 'getting-started/example-deployment/using-the-api.md'
      - 'Advanced User Guide':
        - 'Aggregation': 'getting-started/advanced-guide/aggregation.md'
        - 'Import and Export':
          - 'Using CSV': 'getting-started/advanced-guide/import-export/csv.md'
        - 'Cardinality': 'getting-started/advanced-guide/cardinality.md'
    - 'Gaffer 2.0':
      - Changelist: 'gaffer2.0/changelist.md'
      - Deprecations: 'gaffer2.0/deprecations.md'
      - Dependencies: 'gaffer2.0/dependencies.md'
      - 'Accumulo Migration': 'gaffer2.0/accumulo-migration.md'
      - 'Federation Changes': 'gaffer2.0/federation-changes.md'
      - 'Accumulo Kerberos': 'gaffer2.0/accumulo-kerberos.md'
      - 'Log4j in Gaffer': 'gaffer2.0/log4j.md'
    - 'Developer Docs':
      - 'Development': 'dev/development.md'
      - 'Remote Coding Environments': 'dev/remote-coding-environments.md'
      - 'Managing Dependencies': 'dev/managing-dependencies/managing-dependencies.md'
      - 'Ways of Working': 'dev/ways-of-working.md'
      - 'Sketches custom deserialisation': 'dev/rest-api-sketches.md'
      - Components:
        - 'Components/Maven Modules': 'dev/components/components.md'
        - 'Cache': 'dev/components/cache.md'
        - 'Data': 'dev/components/data.md'
        - 'Graph': 'dev/components/graph.md'
        - 'Store': 'dev/components/store.md'
        - 'Operation': 'dev/components/operation.md'
        - 'Serialisation': 'dev/components/serialisation.md'
        - 'Integration Tests': 'dev/components/integration-test.md'
        - 'Core REST': 'dev/components/core-rest.md'
        - 'Spring REST': 'dev/components/spring-rest.md'
        - 'Accumulo Store': 'dev/components/accumulo-store.md'
        - Libraries:
          - dev/components/libraries/bitmap.md
          - dev/components/libraries/flink.md
          - dev/components/libraries/sketches.md
          - dev/components/libraries/spark.md
          - dev/components/libraries/time.md
    - 'Reference':
      - 'Reference Guide': 'reference/intro.md'
      - 'Glossary': 'reference/glossary.md'
      - 'Javadoc': 'reference/javadoc.md'
      - Properties:
        - 'Properties Guide': 'reference/properties-guide/properties.md'
        - 'Basic Properties': 'reference/properties-guide/basic.md'
        - 'Advanced Properties': 'reference/properties-guide/advanced.md'
        - 'Type Properties': 'reference/properties-guide/type.md'
        - 'Map & Set Properties': 'reference/properties-guide/map-set.md'
      - Predicates:
        - 'Predicates Guide': 'reference/predicates-guide/predicates.md'
        - 'Gaffer Predicates': 'reference/predicates-guide/gaffer-predicates.md'
        - 'Koryphe Predicates': 'reference/predicates-guide/koryphe-predicates.md'
      - 'Binary Operators':
        - 'Binary Operators Guide': 'reference/binary-operators-guide/binary-operators.md'
        - 'Koryphe Operators Guide': 'reference/binary-operators-guide/koryphe-operators.md'
      - Functions:
        - 'Functions Guide': 'reference/functions-guide/functions.md'
        - 'Gaffer Functions': 'reference/functions-guide/gaffer-functions.md'
        - 'Koryphe Functions': 'reference/functions-guide/koryphe-functions.md'
      - Operations:
        - 'Operations Guide': 'reference/operations-guide/operations.md'
        - 'Core Operations': 'reference/operations-guide/core.md'
        - 'Join Operation': 'reference/operations-guide/join.md'
        - 'Get Operations': 'reference/operations-guide/get.md'
        - 'Control Flow Operations': 'reference/operations-guide/flow.md'
        - 'Job Operations': 'reference/operations-guide/job.md'
        - 'Named Operations': 'reference/operations-guide/named.md'
        - 'Export Operations': 'reference/operations-guide/export.md'
        - 'Generate Operations': 'reference/operations-guide/generate.md'
        - 'Flink Operations': 'reference/operations-guide/flink.md'
        - 'HDFS Operations': 'reference/operations-guide/hdfs.md'
        - 'Accumulo Operations': 'reference/operations-guide/accumulo.md'
        - 'Spark Operations': 'reference/operations-guide/spark.md'
        - 'Misc Operations': 'reference/operations-guide/misc.md'
      - Endpoints:
        - 'Endpoints Guide': 'reference/endpoints-guide/endpoints.md'
theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - content.action.edit
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle: &todark
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle: &tolight
        icon: material/weather-sunny
        name: Switch to light mode