site_name: Gaffer Docs
repo_url: https://github.com/gchq/gaffer-doc
repo_name: gchq/gaffer-doc
edit_uri: edit/v2docs/docs/
copyright: Copyright &copy; 2016-2023 Crown Copyright
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gchq/gaffer
      name: Gaffer on GitHub
  version:
    provider: mike
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Europe/London
      strict: true
      exclude:
        - index.md

nav:
    - Home: 'index.md'
    - User Guide:
      - Gaffer Basics:
        - 'What is Gaffer?': 'user-guide/gaffer-basics/what-is-gaffer.md'
        - 'What is a Graph?': 'user-guide/gaffer-basics/what-is-a-graph.md'
        - 'What is JSON?': 'user-guide/gaffer-basics/what-is-json.md'
        - 'What is Python?': 'user-guide/gaffer-basics/what-is-python.md'
      - Getting Started:
        - 'What is Cardinality?': 'user-guide/gaffer-basics/what-is-cardinality.md'
        - 'What is Aggregation?': 'user-guide/gaffer-basics/what-is-aggregation.md'
      - 'Getting Started':
        - 'API': 'user-guide/getting-started/api.md'
        - 'Schema': 'user-guide/getting-started/schema.md'
      - Querying:
        - The Rest API:
          - 'user-guide/query/rest-api/index.md'
          - 'Operations': 'user-guide/query/rest-api/operations.md'
          - 'Filtering': 'user-guide/query/rest-api/filtering.md'
          - Import/Export:
            - 'CSV Data': 'user-guide/query/rest-api/import-export/csv.md'
          - 'Examples': 'user-guide/query/rest-api/examples.md'
        - Python Extension:
          - 'Python Extension Guide': 'user-guide/query/python-extension/python-extension.md'
          - 'Examples': 'user-guide/query/python-extension/examples.md'
        - Gremlin:
          - 'Gremlin Guide': 'user-guide/query/gremlin/gremlin.md'
          - 'Examples': 'user-guide/query/gremlin/examples.md'
    - Development Guide:
      - 'Getting Started': 'development-guide/getting-started.md'
      - 'Example Deployment':
        - 'Project Setup': 'development-guide/example-deployment/project-setup.md'
        - 'Writing the Schema': 'development-guide/example-deployment/writing-the-schema.md'
        - 'Running the Deployment': 'development-guide/example-deployment/running-the-deployment.md'
        - 'Using the API': 'development-guide/example-deployment/using-the-api.md'
      - 'Ways of Working': 'development-guide/ways-of-working.md'
      - 'Remote Coding Environments': 'development-guide/remote-coding-environments.md'
      - 'Extending Gaffer': 'development-guide/extending-gaffer.md'
      - 'Sketches Custom Deserialisation': 'development-guide/rest-api-sketches.md'
      - Project Structure:
        - Components:
          - 'Components/Maven Modules': 'development-guide/project-structure/components/components.md'
          - 'Cache': 'development-guide/project-structure/components/cache.md'
          - 'Data': 'development-guide/project-structure/components/data.md'
          - 'Graph': 'development-guide/project-structure/components/graph.md'
          - 'Store': 'development-guide/project-structure/components/store.md'
          - 'Operation': 'development-guide/project-structure/components/operation.md'
          - 'Serialisation': 'development-guide/project-structure/components/serialisation.md'
          - 'Integration Tests': 'development-guide/project-structure/components/integration-test.md'
          - 'Core REST': 'development-guide/project-structure/components/core-rest.md'
          - 'Spring REST': 'development-guide/project-structure/components/spring-rest.md'
          - 'Accumulo Store': 'development-guide/project-structure/components/accumulo-store.md'
          - Libraries:
            - development-guide/project-structure/components/libraries/bitmap.md
            - development-guide/project-structure/components/libraries/flink.md
            - development-guide/project-structure/components/libraries/sketches.md
            - development-guide/project-structure/components/libraries/spark.md
            - development-guide/project-structure/components/libraries/time.md
        - Maven Dependencies:
          - 'Spring': 'development-guide/project-structure/maven-dependencies/spring.md'
    - Administration Guide:
      - 'Getting Started':
        - 'Docker': 'administration-guide/where-to-run-gaffer/gaffer-docker.md'
        - 'Kubernetes':
          - 'Kubernetes Guide': 'administration-guide/where-to-run-gaffer/kubernetes-guide/kubernetes-guide.md'
          - 'Deploy an Empty Graph': 'administration-guide/where-to-run-gaffer/kubernetes-guide/deploy-empty-graph.md'
          - 'Add your Schema': 'administration-guide/where-to-run-gaffer/kubernetes-guide/deploy-schema.md'
          - 'Change the Graph ID and Description': 'administration-guide/where-to-run-gaffer/kubernetes-guide/change-graph-metadata.md'
          - 'Adding your Own Libraries and Functions': 'administration-guide/where-to-run-gaffer/kubernetes-guide/add-libraries.md'
          - 'Changing Accumulo Passwords': 'administration-guide/where-to-run-gaffer/kubernetes-guide/change-accumulo-passwords.md'
      - 'Store Setup':
        - 'Store Guide': 'administration-guide/gaffer-stores/store-guide.md'
        - 'Accumulo Store': 'administration-guide/gaffer-stores/accumulo-store.md'
        - 'Federated Store': 'administration-guide/gaffer-stores/federated-store.md'
        - 'Map Store':  'administration-guide/gaffer-stores/map-store.md'
        - 'Proxy Store': 'administration-guide/gaffer-stores/proxy-store.md'
      - 'Gaffer Configuration':
        - 'Configuration': 'administration-guide/gaffer-config/config.md'
        - 'Proxy': 'administration-guide/gaffer-config/proxy.md'
        - 'URL': 'administration-guide/gaffer-config/url.md'
      - 'Schema': 'administration-guide/schema.md'
      - 'Import/Export Data': 'administration-guide/import-export-data.md'
      - 'Named Operations': 'administration-guide/named-operations.md'
      - 'Operation Score': 'administration-guide/operation-score.md'
      - 'Security':
        - 'Security Guide': 'administration-guide/security/security-guide.md'
        - 'User Control': 'administration-guide/security/user-control.md'
    - Change Notes:
      - 'Changelist':
        - 'V2.0 Changes': 'change-notes/changelist/v2-changes.md'
      - 'Migrating from V1 to V2':
        - 'Deprecations': 'change-notes/migrating-from-v1-to-v2/deprecations.md'
        - 'Dependencies': 'change-notes/migrating-from-v1-to-v2/dependencies.md'
        - 'Accumulo Migration': 'change-notes/migrating-from-v1-to-v2/accumulo-migration.md'
        - 'Federation Changes': 'change-notes/migrating-from-v1-to-v2/federation-changes.md'
        - 'Accumulo Kerberos': 'change-notes/migrating-from-v1-to-v2/accumulo-kerberos.md'
        - 'Log4j in Gaffer': 'change-notes/migrating-from-v1-to-v2/log4j.md'
    - Reference:
      - 'Reference Guide': 'reference/intro.md'
      - 'Glossary': 'reference/glossary.md'
      - 'Javadoc': 'reference/javadoc.md'
      - Properties:
        - 'Properties Guide': 'reference/properties-guide/properties.md'
        - 'Basic Properties': 'reference/properties-guide/basic.md'
        - 'Advanced Properties': 'reference/properties-guide/advanced.md'
        - 'Type Properties': 'reference/properties-guide/type.md'
        - 'Map & Set Properties': 'reference/properties-guide/map-set.md'
      - Predicates:
        - 'Predicates Guide': 'reference/predicates-guide/predicates.md'
        - 'Gaffer Predicates': 'reference/predicates-guide/gaffer-predicates.md'
        - 'Koryphe Predicates': 'reference/predicates-guide/koryphe-predicates.md'
      - 'Binary Operators':
        - 'Binary Operators Guide': 'reference/binary-operators-guide/binary-operators.md'
        - 'Koryphe Operators Guide': 'reference/binary-operators-guide/koryphe-operators.md'
      - Functions:
        - 'Functions Guide': 'reference/functions-guide/functions.md'
        - 'Gaffer Functions': 'reference/functions-guide/gaffer-functions.md'
        - 'Koryphe Functions': 'reference/functions-guide/koryphe-functions.md'
      - Operations:
        - 'Operations Guide': 'reference/operations-guide/operations.md'
        - 'Core Operations': 'reference/operations-guide/core.md'
        - 'Join Operation': 'reference/operations-guide/join.md'
        - 'Get Operations': 'reference/operations-guide/get.md'
        - 'Control Flow Operations': 'reference/operations-guide/flow.md'
        - 'Job Operations': 'reference/operations-guide/job.md'
        - 'Named Operations': 'reference/operations-guide/named.md'
        - 'Export Operations': 'reference/operations-guide/export.md'
        - 'Generate Operations': 'reference/operations-guide/generate.md'
        - 'Flink Operations': 'reference/operations-guide/flink.md'
        - 'HDFS Operations': 'reference/operations-guide/hdfs.md'
        - 'Accumulo Operations': 'reference/operations-guide/accumulo.md'
        - 'Spark Operations': 'reference/operations-guide/spark.md'
        - 'Misc Operations': 'reference/operations-guide/misc.md'
      - Endpoints:
        - 'Endpoints Guide': 'reference/endpoints-guide/endpoints.md'
theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - content.action.edit
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle: &todark
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle: &tolight
        icon: material/weather-sunny
        name: Switch to light mode