name: Build docs using MkDocs

on:
  push:
    branches:
      - v2docs
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - v2docs
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build only

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build using MkDocs
      run: mkdocs build -s

    - name: Check Links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
        config-file: .github/workflows/mlc_config.json
