name: Update v1docs Gaffer Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'v1 Gaffer Version'
        required: true

jobs:
  update-v1docs-gaffer-version:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
      VERSION_UPDATE_BRANCH: updating-v1docs-gaffer-version-${{ github.event.inputs.version }}
    steps:
    - name: Checkout v1docs
      uses: actions/checkout@v2
      with:
        ref: v1docs
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Setup Github credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Create branch with new v1docs Gaffer Version
      run: |
        newVersion=${{ github.event.inputs.version }}
        git checkout -b ${{ env.VERSION_UPDATE_BRANCH }}

        mvn -q org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.parent.version
        oldVersion=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.parent.version | grep -v '\['`

        sed -i'' "s/version>$oldVersion</version>$newVersion</g" pom.xml
        sed -i'' "s/gaffer2:$oldVersion/gaffer2:$newVersion/g" NOTICES
        sed -i'' "s/gaffer-tools:$oldVersion/gaffer-tools:$newVersion/g" NOTICES
        sed -i'' "s/>Version $oldVersion</>Version $newVersion</g" docs/README.md

        git add .
        git commit -a -m "Updated Gaffer version to $newVersion"
        git push -u origin ${{ env.VERSION_UPDATE_BRANCH }}

    - name: Submit PR
      if: ${{ success() }}
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ env.VERSION_UPDATE_BRANCH }}
        destination_branch: v1docs
        github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
