name: Update Gaffer Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Gaffer Version'
        required: true

jobs:
  update-gaffer-version:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
      VERSION_UPDATE_BRANCH: updating-gaffer-version-${{ github.event.inputs.version }}
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: v1docs
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Setup Github credentials
      run: |
        git config user.name Gaffer
        git config user.email github-actions@github.com

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Update Gaffer Version
      run: ./cd/updateGafferVersion.sh ${{ github.event.inputs.version }}

    - name: Submit PR
      if: ${{ success() }}
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ env.VERSION_UPDATE_BRANCH }}
        destination_branch: v1docs
        github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
